---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
  namespace: kube-system
provisioner: efs.csi.aws.com
allowVolumeExpansion: true
reclaimPolicy : Retain
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-01a4742b267c986bd
  directoryPerms: "700"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
