---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi  # Specify the storage capacity
  accessModes:
    - ReadWriteMany  # EFS supports ReadWriteMany access mode
  persistentVolumeReclaimPolicy: Retain  # Policy for reclaiming the volume
  storageClassName: efs-sc  # Reference to a storage class if you have one
  csi:  # Using the Container Storage Interface
    driver: efs.csi.aws.com  # EFS CSI driver
    volumeHandle: fs-01a4742b267c986bd # Replace with your EFS file system ID

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
