---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-pv
  namespace: kube-system
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy : Retain
mountOptions:
  - tls
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-01a4742b267c986bd
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/hktech"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pv
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-pv
  resources:
    requests:
      storage: 5Gi
